#!/usr/bin/env python3
"""Summarize existing canary artifacts; never starts or changes a server."""
import argparse
import csv
import json
from pathlib import Path
import re


def summarize(folder):
    summary_path = folder / 'summary.json'
    summary = json.loads(summary_path.read_text()) if summary_path.exists() else {}
    requests = json.loads((folder / 'requests.json').read_text())
    rss = list(csv.DictReader((folder / 'rss.csv').open()))
    vram = list(csv.DictReader((folder / 'vram.csv').open()))
    runtime_rss = [float(r['rss_mib']) for r in rss if r['phase'] != 'loading']
    rows = []
    previous_prompt = 0
    for request in requests:
        label = request['label']
        if label.startswith('warmup'):
            continue
        trace = (folder / (label + '.trace.log')).read_text()
        gen = re.search(r'KVMEM_GEN_WALL n=(\d+) ms=([\d.]+) toks=([\d.]+)', trace)
        if not gen:
            continue
        usage = request.get('usage') or (request.get('response') or {}).get('usage')
        if not usage:
            chunks = [json.loads(x[6:]) for x in (folder / (label + '.response.txt')).read_text().splitlines()
                      if x.startswith('data: {')]
            usage = next((x['usage'] for x in reversed(chunks) if x.get('usage')), {})
        fields = dict(re.findall(r'(\w+)=(\S+)', request['trace'][-1]))
        decision = dict(re.findall(r'(\w+)=(\S+)', request['decision'][-1])) if request['decision'] else {}
        perf = dict(re.findall(r'(\w+)=(\S+)', request['perf'][-1])) if request.get('perf') else {}
        speculative = re.findall(r'KVMEM_TRACE spec_stats (.*)', trace)
        spec = dict(re.findall(r'(\w+)=(\S+)', speculative[-1])) if speculative else {}
        gdn = re.findall(r'KVMEM_GDN_PERF (.*)', trace)
        gdn = dict(re.findall(r'(\w+)=(\S+)', gdn[-1])) if gdn else {}
        prompt = usage.get('prompt_tokens', 0)
        prefill_s = request['prefill_ms'][0] / 1000
        phase_rss = [float(x['rss_mib']) for x in rss if x['phase'] == label]
        phase_vram = [float(x['used_mib']) for x in vram if x['phase'] == label]
        row = dict(label=label, prompt_tokens=prompt, new_prompt_tokens=prompt-previous_prompt,
                   generated_tokens=int(gen[1]), prefill_s=prefill_s,
                   decode_s=float(gen[2])/1000, decode_tps=float(gen[3]),
                   ttft_s=request.get('ttft_s'), wall_s=request['elapsed_s'],
                   cache_hit_tokens=usage.get('prompt_cache_hit_tokens'),
                   replay_rows=int(decision.get('replay_rows', fields.get('replayed_rows', 0))),
                   first_s=float(perf.get('first_ms', 0))/1000,
                   replay_s=float(perf.get('replay_ms', 0))/1000,
                   retrieval_s=float(perf.get('retrieval_ms', 0))/1000,
                   path=decision.get('path'), encoder_s=float(fields['encoder_ms'])/1000,
                   mtp_drafted=int(spec.get('n_drafted', 0)),
                   mtp_accepted=int(spec.get('n_accept', 0)),
                   mtp_verify_calls=len(re.findall(r'KVMEM_TRACE spec_verify ', trace)),
                   gdn_fold_s=float(gdn['fold_ms'])/1000 if 'fold_ms' in gdn else None,
                   runtime_rss_peak_mib=max(phase_rss, default=None),
                   vram_peak_mib=max(phase_vram, default=None))
        # Count only newly evaluated input, excluding cached history and output
        # generated by an earlier request. Image input uses logical visual rows.
        new_input_rows = int(fields['new_text_rows']) + int(fields['new_image_rows'])
        row.update(new_input_rows=new_input_rows,
                   first_pass_prefill_tps=new_input_rows/row['first_s'] if row['first_s'] > 0 else None,
                   effective_prefill_tps=new_input_rows/prefill_s if prefill_s > 0 else None)
        rows.append(row)
        previous_prompt = prompt
    if not rows:
        raise ValueError(f'No completed generation records: {folder}')
    with (folder / 'metrics.csv').open('w') as output:
        writer = csv.DictWriter(output, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)
    tools = [r for r in rows if r['label'].startswith('long-tool-')]
    measured = tools or rows
    drafted = sum(r['mtp_drafted'] for r in measured)
    accepted = sum(r['mtp_accepted'] for r in measured)
    prefill_s = sum(r['prefill_s'] for r in measured)
    first_pass_s = sum(r['first_s'] for r in measured)
    new_input_rows = sum(r['new_input_rows'] for r in measured)
    decode_s = sum(r['decode_s'] for r in measured)
    task_input_rows = sum(r['new_input_rows'] for r in rows)
    task_first_s = sum(r['first_s'] for r in rows)
    task_prefill_s = sum(r['prefill_s'] for r in rows)
    task_prefill = dict(request_count=len(rows), new_input_rows=task_input_rows,
                        first_pass_s=task_first_s, total_s=task_prefill_s,
                        first_pass_tps=task_input_rows/task_first_s
                            if all(r['first_s'] > 0 for r in rows) else None,
                        effective_tps=task_input_rows/task_prefill_s)
    result = dict(request_count=len(rows), tool_rounds=len(tools),
                  final_prompt_tokens=rows[-1]['prompt_tokens'],
                  final_total_tokens=rows[-1]['prompt_tokens']+rows[-1]['generated_tokens'],
                  tool_prefill_s=prefill_s, tool_decode_s=decode_s,
                  effective_prefill_tps=new_input_rows/prefill_s,
                  first_pass_prefill_tps=new_input_rows/first_pass_s
                      if all(r['first_s'] > 0 for r in measured) else None,
                  # Whole-task rates include the long benchmark's base request.
                  # Sum input and time before dividing; never average row rates.
                  task_prefill=task_prefill,
                  aggregate_decode_tps=sum(r['generated_tokens'] for r in measured)/decode_s,
                  mtp_drafted=drafted, mtp_accepted=accepted,
                  mtp_accept_pct=100*accepted/drafted if drafted else None,
                  total_request_wall_s=sum(r['wall_s'] for r in rows),
                  replay_rounds=sum(r['replay_rows']>0 for r in measured),
                  total_replay_rows=sum(r['replay_rows'] for r in measured),
                  first_pass_s=first_pass_s,
                  replay_s=sum(r['replay_s'] for r in measured),
                  retrieval_s=sum(r['retrieval_s'] for r in measured),
                  peak_runtime_rss_mib=max(runtime_rss, default=None),
                  peak_loading_rss_mib=max((float(r['rss_mib']) for r in rss if r['phase']=='loading'), default=None),
                  peak_vram_mib=max(float(r['used_mib']) for r in vram),
                  min_free_vram_mib=min(float(r['free_mib']) for r in vram),
                  peak_process_swap_mib=max((float(r['swap_mib']) for r in rss if r.get('swap_mib')), default=None),
                  last_request=rows[-1], options=summary.get('options'))
    (folder / 'metrics.json').write_text(json.dumps(result, indent=2, ensure_ascii=False)+'\n')
    return result


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('folders', type=Path, nargs='+')
    args = parser.parse_args()
    for folder in args.folders:
        print(folder, json.dumps(summarize(folder), ensure_ascii=False))
