// This file has been autogenerated by generate_cu_files.py, do not edit manually.

#include "../fattn-mma-kvarn-decode.cuh"
#include "../fattn-kvarn-vec.cuh"

DECL_FATTN_KVARN_DECODE_CASE(128, 8, 6);
DECL_FATTN_KVARN_DECODE_CASE(256, 8, 6);
DECL_FATTN_KVARN_DECODE_CASE(512, 8, 6);
DECL_FATTN_KVARN_VEC_CASE(256, 8, 6);
