// This file has been autogenerated by generate_cu_files.py, do not edit manually.

#include "../fattn-mma-kvarn-window-common.cuh"

#define DECL_FATTN_KVARN_WINDOW_COMMON(D) \
    template ggml_cuda_fattn_kvarn_window_dequant_kernel_t \
        ggml_cuda_fattn_kvarn_window_dequant_get_kernel<D>(); \
    template ggml_cuda_fattn_kvarn_window_finalize_kernel_t \
        ggml_cuda_fattn_kvarn_window_finalize_get_kernel<D>()

DECL_FATTN_KVARN_WINDOW_COMMON(128);
DECL_FATTN_KVARN_WINDOW_COMMON(256);
DECL_FATTN_KVARN_WINDOW_COMMON(512);

#undef DECL_FATTN_KVARN_WINDOW_COMMON
