// This file has been autogenerated by generate_cu_files.py, do not edit manually.

#include "../fattn-mma-kvarn-decode-combine.cuh"

#define DECL_FATTN_KVARN_DECODE_COMBINE(D) \
    template ggml_cuda_fattn_kvarn_decode_combine_kernel_t \
        ggml_cuda_fattn_kvarn_decode_combine_get_kernel<D>()

DECL_FATTN_KVARN_DECODE_COMBINE(128);
DECL_FATTN_KVARN_DECODE_COMBINE(256);
DECL_FATTN_KVARN_DECODE_COMBINE(512);

#undef DECL_FATTN_KVARN_DECODE_COMBINE
