// This file has been autogenerated by generate_cu_files.py, do not edit manually.

#include "../fattn-mma-kvarn-case.cuh"

DECL_FATTN_MMA_KVARN_CASE(128, 128, 4, 4);
DECL_FATTN_MMA_KVARN_CASE(256, 256, 4, 4);
DECL_FATTN_MMA_KVARN_CASE(512, 512, 4, 4);
