// This file has been autogenerated by generate_cu_files.py, do not edit manually.

#include "../fattn-mma-kvarn-case.cuh"

#if !defined(GGML_USE_MUSA)
DECL_FATTN_MMA_KVARN_CASE(128, 128, 16, 8);
template bool ggml_cuda_fattn_kvarn_wide_mma_supported<128, 128, 16, 8>(ggml_backend_cuda_context &, const ggml_tensor *);
DECL_FATTN_MMA_KVARN_CASE(256, 256, 16, 8);
template bool ggml_cuda_fattn_kvarn_wide_mma_supported<256, 256, 16, 8>(ggml_backend_cuda_context &, const ggml_tensor *);
#endif
