import { chromium } from '../build-ui/node_modules/playwright/index.mjs';
import fs from 'node:fs';
fs.mkdirSync('logs/webui',{recursive:true});
const browser=await chromium.launch({executablePath:process.env.CHROMIUM,headless:true,args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:1280,height:900}});
const errors=[],requests=[];page.on('pageerror',e=>errors.push(String(e)));page.on('request',r=>requests.push(r.url()));
try {
 await page.goto(process.env.KVMEM_UI_TEST_URL || 'http://127.0.0.1:18400/');
 await page.getByRole('button',{name:'参数',exact:true}).click();
 await page.getByLabel('思考 token 预算',{exact:true}).fill('0');
 await page.getByLabel('最大输出',{exact:true}).fill('128');
 await page.getByLabel('消息输入').fill('What is 2+3? Answer with the number only.');
 await page.getByRole('button',{name:'发送',exact:true}).click();
 await page.getByText(/tok\/s/).waitFor({timeout:90000});
 await page.getByRole('button',{name:'新建对话',exact:true}).click();
 await page.getByLabel('消息输入').fill('Write a short HTML page with a heading Hello, in a fenced code block.');
 await page.getByRole('button',{name:'发送',exact:true}).click();
 await page.getByText(/tok\/s/).waitFor({timeout:90000});
 await page.locator('article:not(.user) pre').first().waitFor();
 await page.screenshot({path:'logs/webui/desktop.png',fullPage:true});
 await page.reload();
 await page.locator('nav button').filter({hasText:'What is 2+3'}).click();
 await page.getByText(/tok\/s/).waitFor();
 if ((await page.locator('article').count())!==2) throw Error('history not restored');
 await page.getByRole('button',{name:'参数',exact:true}).click();
 await page.getByLabel('最大输出',{exact:true}).fill('512');
 await page.getByLabel('消息输入').fill('List the integers from 1 to 200, one per line.');
 await page.getByRole('button',{name:'发送',exact:true}).click();
 await page.getByRole('button',{name:'停止生成',exact:true}).waitFor();
 await page.waitForTimeout(700);
 await page.getByRole('button',{name:'停止生成',exact:true}).click();
 await page.getByText('已中止',{exact:true}).waitFor();
 await page.getByLabel('最大输出',{exact:true}).fill('64');
 await page.getByLabel('消息输入').fill('What is 3+4? Answer with the number only.');
 await page.getByRole('button',{name:'发送',exact:true}).click();
 await page.getByRole('button',{name:'发送',exact:true}).waitFor({timeout:90000});
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:'logs/webui/mobile.png',fullPage:true});
 const forbidden=requests.filter(u=>/\/(tools|slots|models\/|v1\/stream|cors-proxy)/.test(u));
 fs.writeFileSync('logs/webui/browser-results.json',JSON.stringify({errors,forbidden,requests},null,2));
 if (errors.length || forbidden.length) throw Error(JSON.stringify({errors,forbidden}));
 console.log('browser chat, history, code rendering, cancellation and continuation passed');
} finally {await browser.close();}
